name: Generate Snake

on:
  schedule:
    # every 12 hours
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks out the repository
      - uses: actions/checkout@v3

      # Generates the snake  
      - uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: quarkum-0
          # Generate files in the `dist` directory
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Create the `dist` directory if it does not exist
      - run: mkdir -p dist

      # Check out the `output` branch
      - name: Checkout Output Branch
        run: |
          git fetch origin output || git checkout -b output
          git checkout output

      # Commit and push changes to `output` branch
      - name: Commit and Push Changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add dist/github-contribution-grid-snake.gif dist/github-contribution-grid-snake.svg
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update contribution graph"
            git push origin output
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Deploy the content to GitHub Pages
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
